// =============================================================================
// DramaCPS Per-Drama Links (Non-ReelShort platforms)
// Auto-extracted from dramacps.com on 2026-09-01
// 158 dramas mapped (130 original + 18 from v5 + 10 from v6 episode names)
// ReelShort links excluded (handled by RS Boost)
// =============================================================================

export interface DramaCpsEntry {
  link: string;
  platform: string;
}

export const DRAMACPS_PER_DRAMA: Record<string, DramaCpsEntry> = {
  '(Dubbed) His One-Year Wife, His Forever Love': { link: 'https://r.reelsgo.tv/B4EX3xplHvwg', platform: 'KALOSTV' },
  '(Dubbed) My Secret Child With The CEO': { link: 'https://r.reelsgo.tv/l0L78y6CzRA_', platform: 'GOODSHORT' },
  '100% Destined for Your Love': { link: 'https://r.reelsgo.tv/5XY148Wi9Yxo', platform: 'YOURCHANNEL' },
  '[Dubbed] Heart of the Dragon': { link: 'https://r.reelsgo.tv/F11p7nE_JKrT', platform: 'TOUCHSHORT' },
  '[Dubbed] Love After Divorce: The Elusive Wife': { link: 'https://r.reelsgo.tv/B4EX3xplHvwg', platform: 'KALOSTV' },
  '[Dubbed] Love between fairy and devil': { link: 'https://r.reelsgo.tv/N2s5nTHN8SG_', platform: 'FLAREFLOW' },
  '[Dubbed] She Was Never His': { link: 'https://r.reelsgo.tv/PjyoOYuF4VX6', platform: 'SEREAL+' },
  '[Dubbed] The Elixir Pact: Married to the Hidden Master': { link: 'https://r.reelsgo.tv/BerB6FVvz4a2', platform: 'GOODSHORT' },
  '[Dubbed] The Forbidden Promise: Lord Jiang\'s Consort': { link: 'https://r.reelsgo.tv/B49CsYkIrLeS', platform: 'FLICKREELS' },
  '[Dubbed]Veiled War God: Protect the Heiress': { link: 'https://r.reelsgo.tv/p5Yb1O_Qls9e', platform: 'GOODSHORT' },
  '[ENG DUB] He Knows Your Name, He Owns Your Fate': { link: 'https://r.reelsgo.tv/fjVMQ2K1dRAj', platform: 'FLAREFLOW' },
  '[ENG DUB] Sisters Against the World\'s Judgment': { link: 'https://r.reelsgo.tv/14SRQIuxgUm_', platform: 'YOURCHANNEL' },
  '[ENG DUB] The Phoenix in the Dust': { link: 'https://r.reelsgo.tv/Ru4zE3n9iA8N', platform: 'STARDUSTTV' },
  '[ENG DUB] What the Fire Left Standing': { link: 'https://r.reelsgo.tv/DmSxPMJ0Olr4', platform: 'FLAREFLOW' },
  'A Flash Marriage With The Billionaire Tycoon': { link: 'https://r.reelsgo.tv/aHsu55aQz-Rh', platform: 'SHORTMAX' },
  'A Love Contract with the Zombie King': { link: 'https://r.reelsgo.tv/JigEokxxYib6', platform: 'FLAREFLOW' },
  'A Sweet Contract with the Mafia Boss': { link: 'https://r.reelsgo.tv/l0L78y6CzRA_', platform: 'GOODSHORT' },
  'After I Bought Sperm, the Alpha Claimed Me': { link: 'https://r.reelsgo.tv/Kb7csvrF53wO', platform: 'FLAREFLOW' },
  'After She Cheated with a Star, I Pulled Her from Every Screen': { link: 'https://r.reelsgo.tv/DfxSwHxpLoKo', platform: 'YOURCHANNEL' },
  'After the Divorce, I Made Him Lose Everything': { link: 'https://r.reelsgo.tv/B4EX3xplHvwg', platform: 'KALOSTV' },
  'After the Divorce, the Mafia Boss Went crazy': { link: 'https://r.reelsgo.tv/bbXYF1Ypauza', platform: 'FLICKREELS' },
  'Alpha, You Have A Secret Cub!': { link: 'https://r.reelsgo.tv/Mpp2hn1BZ2mS', platform: 'FLAREFLOW' },
  'Back to You, Back to Love': { link: 'https://r.reelsgo.tv/xsJmREnOSFC9', platform: 'YOURCHANNEL' },
  'Back with Five Heirs to Claim What\'s Mine': { link: 'https://r.reelsgo.tv/DmSxPMJ0Olr4', platform: 'FLAREFLOW' },
  'Beneath Her Gown: The Master\'s Claimed Wolf Pet': { link: 'https://r.reelsgo.tv/zh39Dv7Muubj', platform: 'FLICKREELS' },
  'Billionaire Brothers and Their Country Brides': { link: 'https://r.reelsgo.tv/fynyA3XAHncw', platform: 'GOODSHORT' },
  'Billionaire Heiress VS Her Murderer Husband': { link: 'https://r.reelsgo.tv/uWzI2iupLUbO', platform: 'STARDUSTTV' },
  'Bitchy BFF It\'s Your Turn to Pay': { link: 'https://r.reelsgo.tv/XEBP8SJZxHzF', platform: 'GOODSHORT' },
  'Blasting Through the Galaxy with the Queen': { link: 'https://r.reelsgo.tv/ddDhMvlxKtbV', platform: 'STARDUSTTV' },
  'Blood and Bones of the Disowned Daughter': { link: 'https://r.reelsgo.tv/rqzUxXhWbeZ_', platform: 'KALOSTV' },
  'Code Name: Villain Stepmom': { link: 'https://r.reelsgo.tv/eu8jtUa7iTjy', platform: 'GOODSHORT' },
  'Comeback of a Hidden Empress': { link: 'https://r.reelsgo.tv/g1JYD8b5Of_0', platform: 'GOODSHORT' },
  'Crimson Palace: The Maid\'s Rise to the Throne': { link: 'https://r.reelsgo.tv/TaMlOaucMbRO', platform: 'KALOSTV' },
  'Cursed: I Married the Don in My Sister\'s Place': { link: 'https://r.reelsgo.tv/wfpLaLcRti14', platform: 'SHORTMAX' },
  'Daddy Mommy\'s In the Sky': { link: 'https://r.reelsgo.tv/5sR0Vf6MoJPT', platform: 'GOODSHORT' },
  'Desserts Lies and Love': { link: 'https://r.reelsgo.tv/N2s5nTHN8SG_', platform: 'FLAREFLOW' },
  'Divorce The Billionaire Husband': { link: 'https://r.reelsgo.tv/0iENWHG3Ttg5', platform: 'FLAREFLOW' },
  'Divorce The Billionaire Husband 2.0': { link: 'https://r.reelsgo.tv/0iENWHG3Ttg5', platform: 'FLAREFLOW' },
  'Don\'t Mess with the New Guard': { link: 'https://r.reelsgo.tv/dZQ36QyRbfzj', platform: 'FLAREFLOW' },
  'Dragon King': { link: 'https://r.reelsgo.tv/YzIm0_Xct5PP', platform: 'DRAMABOX' },
  'Dumped the Groom, Married the Billionaire': { link: 'https://r.reelsgo.tv/_PplJ5eQXeAX', platform: 'DRAMABOX' },
  'Dying After Ten Years for His Sin': { link: 'https://r.reelsgo.tv/kY5Nt5R8HodR', platform: 'STARDUSTTV' },
  'Earth-King Returns from the Shadow': { link: 'https://r.reelsgo.tv/8uaGNQU2NpMH', platform: 'KALOSTV' },
  'Exiled to the Abyss: Return of the Fire God': { link: 'https://r.reelsgo.tv/LujhW6njuOFH', platform: 'FLAREFLOW' },
  'Fallen Hero Reborn as Captain 8-Year-Old Rising': { link: 'https://r.reelsgo.tv/vq-azTgT1owX', platform: 'GOODSHORT' },
  'Falling for My Dad\'s Best Friend': { link: 'https://r.reelsgo.tv/QQHH6IAPdLOv', platform: 'GOODSHORT' },
  'For The One Who Loved Me First': { link: 'https://r.reelsgo.tv/H4I4o8tsG2Rw', platform: 'SEREAL+' },
  'Forbidden Love with My Husband\'s Son': { link: 'https://r.reelsgo.tv/7StNbc_Lw9Hx', platform: 'KALOSTV' },
  'Forever Her Guardians: Her Three Knights': { link: 'https://r.reelsgo.tv/QQHH6IAPdLOv', platform: 'GOODSHORT' },
  'From Rags to The Hidden Heir\'s Bride': { link: 'https://r.reelsgo.tv/iimNLVNw8xld', platform: 'SEREAL+' },
  'From Rejected to the Alpha Queen': { link: 'https://r.reelsgo.tv/zFXQFrdjVpBF', platform: 'FLAREFLOW' },
  'Getting Even: the Secret Prodigy’s playbook': { link: 'https://r.reelsgo.tv/J9DmhpPb9kxY', platform: 'FLAREFLOW' },
  'Gladiator Prince Unshackled by Love': { link: 'https://r.reelsgo.tv/9PHFXanGT_Se', platform: 'GOODSHORT' },
  'He Dumped Me Live. I Took Over His Team': { link: 'https://r.reelsgo.tv/r02x46MzgsX7', platform: 'KALOSTV' },
  'He Knew I Was the Wrong Bride': { link: 'https://r.reelsgo.tv/nMz-v1L0cF3C', platform: 'GOODSHORT' },
  'He Saved a Boy Who Returns a Billion': { link: 'https://r.reelsgo.tv/aeUX8T1Gigvv', platform: 'GOODSHORT' },
  'He Took A Mistress I Took the Sky': { link: 'https://r.reelsgo.tv/gjkCEeSZo8p9', platform: 'GOODSHORT' },
  'He\'s Too Late for Her Mafia Majesty': { link: 'https://r.reelsgo.tv/0iENWHG3Ttg5', platform: 'FLAREFLOW' },
  'Her Second Marriage, Her Golden Era': { link: 'https://r.reelsgo.tv/0u7Zu_LdJSz_', platform: 'GOODSHORT' },
  'Hidden Ace Makes Cocky Captain Beg for Mercy': { link: 'https://r.reelsgo.tv/jDeuMbmZNx7x', platform: 'GOODSHORT' },
  'I Am the First, the Last, and the Only': { link: 'https://r.reelsgo.tv/z5sCrqvjrVFA', platform: 'STARDUSTTV' },
  'I Dumped the Heirs for the Alpha King': { link: 'https://r.reelsgo.tv/OIFc9XFnqKzL', platform: 'KALOSTV' },
  'I Helped My Husband’s Brother Take The Mafia Throne': { link: 'https://r.reelsgo.tv/VCHjiDjsLksw', platform: 'KALOSTV' },
  'I Was Sent to Spy on the Mad Mafia Heir': { link: 'https://r.reelsgo.tv/nMz-v1L0cF3C', platform: 'GOODSHORT' },
  'I\'m the Mafia Girl Boss and He\'s My Man': { link: 'https://r.reelsgo.tv/XGL0_1BC4h46', platform: 'FLAREFLOW' },
  'King of the Flooded World': { link: 'https://r.reelsgo.tv/TDlJknwwR15R', platform: 'FLAREFLOW' },
  'Leashed to My Demanding Boss 24/7': { link: 'https://r.reelsgo.tv/vtqr8OD-_klc', platform: 'GOODSHORT' },
  'Living as the Villainess: The Princess\'s Divorce Agenda': { link: 'https://r.reelsgo.tv/0iENWHG3Ttg5', platform: 'FLAREFLOW' },
  'Love as I Remember': { link: 'https://r.reelsgo.tv/hIf_yl3xgfPt', platform: 'GOODSHORT' },
  'Love Lost in the Space': { link: 'https://r.reelsgo.tv/u5ExhX5i3NVy', platform: 'KALOSTV' },
  'Mama with Might: Two Little Reasons to Love': { link: 'https://r.reelsgo.tv/7StNbc_Lw9Hx', platform: 'KALOSTV' },
  'Match Point': { link: 'https://r.reelsgo.tv/XmBLHpbZQwgV', platform: 'YOURCHANNEL' },
  'More Than a Trainer: The Secret Matriarch': { link: 'https://r.reelsgo.tv/V_LkP8K0TpOh', platform: 'GOODSHORT' },
  'My ex-wife came to remarry me the day my billionaire wife showed up.': { link: 'https://r.reelsgo.tv/SjJExLkysY0s', platform: 'FLAREFLOW' },
  'My Ex-Wife Wants Me Back Too Late': { link: 'https://r.reelsgo.tv/wU2_9US7NcZN', platform: 'SHORTMAX' },
  'My Fake Fiancé Is the War GodOne night with the God of War leaves Serena pregnant with a forbidden child. To save the baby, she strikes a bargain with Fate and forgets the father completely. But when she enters his temple, Ares is drawn to her with an obsession he can’t explain. And he’s already willing to give up everything for her.HistoricalRomanceFantasy3.7K104.1KPlay': { link: 'https://r.reelsgo.tv/dZQ36QyRbfzj', platform: 'FLAREFLOW' },
  'My Fiancé Betrayed Me, So I Bankrupted Him': { link: 'https://r.reelsgo.tv/ZLoo1fJNsKM5', platform: 'STARDUSTTV' },
  'My Forbidden Professor Broke Every Rule for Me': { link: 'https://r.reelsgo.tv/lekmHJZfO_t8', platform: 'DRAMABOX' },
  'My Heir Was In The Stable': { link: 'https://r.reelsgo.tv/nMz-v1L0cF3C', platform: 'GOODSHORT' },
  'My Secret Affair with the Duke': { link: 'https://r.reelsgo.tv/xlWSE0F6TGZx', platform: 'FLAREFLOW' },
  'My Sister is Not Someone to Mess with': { link: 'https://r.reelsgo.tv/IXkYLccKOW_c', platform: 'KALOSTV' },
  'My Vampire Lord': { link: 'https://r.reelsgo.tv/AMhuX08r1G5G', platform: 'FLAREFLOW' },
  'Peasant Daddy Rules the World': { link: 'https://r.reelsgo.tv/DF2g7q3E5_MP', platform: 'GOODSHORT' },
  'Playing the Fool: The CEO Wife’s Revenge': { link: 'https://r.reelsgo.tv/65zXibIHv8tw', platform: 'YOURCHANNEL' },
  'Power of Three Set me Free': { link: 'https://r.reelsgo.tv/9lcpM-0GtDfw', platform: 'GOODSHORT' },
  'Reborn as A Kingmaker of My Useless Chaebol Dad': { link: 'https://r.reelsgo.tv/dBaaOrFoUA28', platform: 'GOODSHORT' },
  'Regret Yet? Your Goddess Is Your Ex-Wife': { link: 'https://r.reelsgo.tv/65zXibIHv8tw', platform: 'YOURCHANNEL' },
  'Regret！Your Husband is A Tycoon!': { link: 'https://r.reelsgo.tv/sdIVg3HeEOkj', platform: 'SHORTMAX' },
  'Return of the Abandoned Heiress': { link: 'https://r.reelsgo.tv/j_05hfMXsc1S', platform: 'GOODSHORT' },
  'Return of the Exiled Dragon Heir': { link: 'https://r.reelsgo.tv/l6mdspZGNvCG', platform: 'DRAMABOX' },
  'Revenge for The Truth in Her Diary': { link: 'https://r.reelsgo.tv/ddDhMvlxKtbV', platform: 'STARDUSTTV' },
  'Secret Marriage Swap, The War God’s Late Remorse': { link: 'https://r.reelsgo.tv/J9DmhpPb9kxY', platform: 'FLAREFLOW' },
  'Sex in the Bathroom with a Mafia Don': { link: 'https://r.reelsgo.tv/qn3WA8vr5Yld', platform: 'YOURCHANNEL' },
  'Slumdog Million-Dollar Star': { link: 'https://r.reelsgo.tv/Joh8tcRq2h1p', platform: 'FLAREFLOW' },
  'Small Town Girl Finds Her Mr. Big Time': { link: 'https://r.reelsgo.tv/XGL0_1BC4h46', platform: 'FLAREFLOW' },
  'Sweet Revenge for the Wrong Diagnosis': { link: 'https://r.reelsgo.tv/J9DmhpPb9kxY', platform: 'FLAREFLOW' },
  'Ten Years Betrayed, Ten Years Awaited': { link: 'https://r.reelsgo.tv/FwUXn2O-I9xQ', platform: 'STARDUSTTV' },
  'The 100th Divorce Was Final': { link: 'https://r.reelsgo.tv/jXSHaQH-sQXc', platform: 'GOODSHORT' },
  'The Alpha\'s Rejected Mate': { link: 'https://r.reelsgo.tv/Mpp2hn1BZ2mS', platform: 'FLAREFLOW' },
  'The Alpha’s Forbidden Vampire Bride': { link: 'https://r.reelsgo.tv/iimNLVNw8xld', platform: 'SEREAL+' },
  'The Baby Plan: Romancing The Parents': { link: 'https://r.reelsgo.tv/zh39Dv7Muubj', platform: 'FLICKREELS' },
  'The Beast King Worships the Worthless': { link: 'https://r.reelsgo.tv/QqAV_Sw9SRu8', platform: 'KALOSTV' },
  'The Beta\'s Regret, She Won\'t Beg This Time': { link: 'https://r.reelsgo.tv/E8Hvbs4-0vt-', platform: 'TOUCHSHORT' },
  'The Billionaire Married a Homeless Girl': { link: 'https://r.reelsgo.tv/XGL0_1BC4h46', platform: 'FLAREFLOW' },
  'The Billionaire’s Rescue': { link: 'https://r.reelsgo.tv/yHW0ikT1sq2i', platform: 'DRAMABOX' },
  'The Bride Who Walked Away': { link: 'https://r.reelsgo.tv/rzJ_zamEgsql', platform: 'FLAREFLOW' },
  'The Canary of the Mafia Boss': { link: 'https://r.reelsgo.tv/VNr-rc2Jb2lF', platform: 'FLAREFLOW' },
  'The Curse of the Midas Touch': { link: 'https://r.reelsgo.tv/LujhW6njuOFH', platform: 'FLAREFLOW' },
  'The Day She Left, Stocks Fell': { link: 'https://r.reelsgo.tv/GMfA4KJoRa5X', platform: 'KALOSTV' },
  'The Delivery Boy Is a Racing God': { link: 'https://r.reelsgo.tv/xWkJSPj2yKaX', platform: 'FLAREFLOW' },
  'The Doctor They Threw Off the Plane': { link: 'https://r.reelsgo.tv/fyrochK_CQux', platform: 'GOODSHORT' },
  'The Ex-Con Dragon Lord': { link: 'https://r.reelsgo.tv/c5bf5kjcg-N2', platform: 'SHORTMAX' },
  'The Foster Son of the Iron Crown': { link: 'https://r.reelsgo.tv/B4EX3xplHvwg', platform: 'KALOSTV' },
  'The Fox Cuts Her Tails for Vengeance': { link: 'https://r.reelsgo.tv/ddDhMvlxKtbV', platform: 'STARDUSTTV' },
  'The Fruit Vendor Who Ruled the Dragon Temple': { link: 'https://r.reelsgo.tv/QqAV_Sw9SRu8', platform: 'KALOSTV' },
  'The Heiress and the Tailor King': { link: 'https://r.reelsgo.tv/p5Yb1O_Qls9e', platform: 'GOODSHORT' },
  'The Heiress Returns': { link: 'https://r.reelsgo.tv/mCWlRXH8o-1b', platform: 'TOUCHSHORT' },
  'The Honey Trap Heir': { link: 'https://r.reelsgo.tv/neBvnku41lB8', platform: 'KALOSTV' },
  'The Law of My Body: A Secret Therapy': { link: 'https://r.reelsgo.tv/aTIctVayHge3', platform: 'DRAMABOX' },
  'The Mafia Boss My Husband Betrayed': { link: 'https://r.reelsgo.tv/VNr-rc2Jb2lF', platform: 'FLAREFLOW' },
  'The Maid Who Ran From the Don': { link: 'https://r.reelsgo.tv/b3JjmZb93_7v', platform: 'SHORTMAX' },
  'The Mogul Behind the Counter': { link: 'https://r.reelsgo.tv/qA3uhhy1Gh7q', platform: 'YOURCHANNEL' },
  'The Phoenix\'s Rebirth for Revenge': { link: 'https://r.reelsgo.tv/J9DmhpPb9kxY', platform: 'FLAREFLOW' },
  'The Prison Made Her A Queen AGAIN': { link: 'https://r.reelsgo.tv/ddDhMvlxKtbV', platform: 'STARDUSTTV' },
  'The Queen Strikes Back with Three Tycoons': { link: 'https://r.reelsgo.tv/5Y9yb9nw_4ri', platform: 'SEREAL+' },
  'The reborn wolf king begs me to remarry': { link: 'https://r.reelsgo.tv/pPvGb8_dbN2M', platform: 'STARDUSTTV' },
  'The Second Address: Double Life': { link: 'https://r.reelsgo.tv/8JDp5OcYrqkE', platform: 'FLAREFLOW' },
  'The Secret Legend: My Husband Is a Medical Genius': { link: 'https://r.reelsgo.tv/lDWx0s0tBQli', platform: 'FLAREFLOW' },
  'The Surgeon You Shouldn\'t Have Crossed': { link: 'https://r.reelsgo.tv/Mpp2hn1BZ2mS', platform: 'FLAREFLOW' },
  'The Transmigrated Sweetheart Stole My Night': { link: 'https://r.reelsgo.tv/xlWSE0F6TGZx', platform: 'FLAREFLOW' },
  'The Trash Miner Is the Secret King of Golantis': { link: 'https://r.reelsgo.tv/AftBvAZYUnqH', platform: 'GOODSHORT' },
  'The Tyrant\'s Max-Level Dragon Bride': { link: 'https://r.reelsgo.tv/RbcPxZIA-i7m', platform: 'SEREAL+' },
  'The Vampire King\'s Runaway Bride': { link: 'https://r.reelsgo.tv/iimNLVNw8xld', platform: 'SEREAL+' },
  'The Vampire Prince\'s Bride': { link: 'https://r.reelsgo.tv/iimNLVNw8xld', platform: 'SEREAL+' },
  'The Veteran\'s Promise': { link: 'https://r.reelsgo.tv/m4D-PhWKX9Ox', platform: 'GOODSHORT' },
  'The Weakest Boy Is the King of the Dead': { link: 'https://r.reelsgo.tv/OIFc9XFnqKzL', platform: 'KALOSTV' },
  'The Wedding That Will Never Be': { link: 'https://r.reelsgo.tv/O5v8EZMaRZai', platform: 'GOODSHORT' },
  'They Bet I\'d Cry, I Bet They\'d Fall': { link: 'https://r.reelsgo.tv/fyrochK_CQux', platform: 'GOODSHORT' },
  'Too Late to Beg the Wolf Queen': { link: 'https://r.reelsgo.tv/J9DmhpPb9kxY', platform: 'FLAREFLOW' },
  'Too Late, Fox. I Chose the Wolf': { link: 'https://r.reelsgo.tv/J9DmhpPb9kxY', platform: 'FLAREFLOW' },
  'Too Late, My Alpha': { link: 'https://r.reelsgo.tv/hwWUjnbrGp2h', platform: 'GOODSHORT' },
  'Touch the Don’s Wife.Pay the Price': { link: 'https://r.reelsgo.tv/Mpp2hn1BZ2mS', platform: 'FLAREFLOW' },
  'Trapped and Redeemed By His Love': { link: 'https://r.reelsgo.tv/N9_TyN928v0D', platform: 'KALOSTV' },
  'When the Wolf Fell in Love': { link: 'https://r.reelsgo.tv/H4I4o8tsG2Rw', platform: 'SEREAL+' },
  'Wolf of the North': { link: 'https://r.reelsgo.tv/TaMlOaucMbRO', platform: 'KALOSTV' },
  'Wolves at Her Back, Dragons at Her Side': { link: 'https://r.reelsgo.tv/5Y9yb9nw_4ri', platform: 'SEREAL+' },
  'Wrath of the Zeus‘s Son': { link: 'https://r.reelsgo.tv/PP8CYIHtcEMH', platform: 'SHORTMAX' },
  'Your Loser Husband Is the War God': { link: 'https://r.reelsgo.tv/xsJmREnOSFC9', platform: 'YOURCHANNEL' },
  '[Dubbed] Spoiled by the boss': { link: 'https://r.reelsgo.tv/1Um3u4Xv4wUF', platform: 'KALOSTV' },
  '[Dubbed] The Petite Healer': { link: 'https://r.reelsgo.tv/zW0q59EpZ9WU', platform: 'STARDUSTTV' },
  '[ENG DUB] Rise Built on Forgotten Betrayals': { link: 'https://r.reelsgo.tv/w4MwHKyALa7F', platform: 'GOODSHORT' },
  'By Marrying North I Won His Remorse': { link: 'https://r.reelsgo.tv/6hsPuhDyu--w', platform: 'GOODSHORT' },
  'Daddy Don\'s Forbidden Pet': { link: 'https://r.reelsgo.tv/H9tPMTYaK0uZ', platform: 'GOODSHORT' },
  'Fake Queen Bee, I\'m the true Heiress!': { link: 'https://r.reelsgo.tv/SSXu7yS9I4qY', platform: 'YOURCHANNEL' },
  'From Mudblood to Atlantis\' Owner': { link: 'https://r.reelsgo.tv/SHNYfKAzedJx', platform: 'GOODSHORT' },
  'The Last Month of No Masters': { link: 'https://r.reelsgo.tv/vP5W847Z-nIm', platform: 'GOODSHORT' },
  'The Trash Heiress Is A Dragon Master': { link: 'https://r.reelsgo.tv/tA12-MdxytOP', platform: 'GOODSHORT' },
  'Worlds Apart': { link: 'https://r.reelsgo.tv/jQqKqe73cTG3', platform: 'GOODSHORT' },
};