// RS Boost per-drama CPS links (resource promotion links)
// Auto-extracted from RS Boost dashboard on 2026-08-31
// These are App deep links that open directly to the specific drama.

export const RS_BOOST_PER_DRAMA: Record<string, string> = {
  '99 Forgiveness, One Goodbye': 'https://reelslink.com/cps/jvR8rt',
  'A Father\'s Regret': 'https://reelslink.com/cps/iGpoAB',
  'Big Bad Husband, Please Wake Up!': 'https://reelslink.com/cps/P1aoAF',
  'Bite the Exorcist Heir': 'https://reelslink.com/cps/oS6u6Y',
  'Boyfriend from the Future': 'https://reelslink.com/cps/C7th9f',
  'Crowned in His Claws': 'https://reelslink.com/cps/X9Ycul',
  'Curvy Bloom, Sweet Surrender': 'https://reelslink.com/cps/BfGb4y',
  'Don\'t Mess with a Prep School Princess': 'https://reelslink.com/cps/5jqzLU',
  'Dumped the Groom, Married the Billionaire': 'https://reelslink.com/cps/HOy1T3',
  'Dying After Ten Years for His Sin': 'https://reelslink.com/cps/Ha4uzO',
  'Everything Plus, Everyone Else Shuts': 'https://reelslink.com/cps/EQta4y',
  'Fake Queen Bee, I\'m the true Heiress!': 'https://reelslink.com/cps/TpZc09',
  'Falling for My Dad\'s Best Friend': 'https://reelslink.com/cps/YlCfGs',
  'Final Skill: Win Her Heart': 'https://reelslink.com/cps/AT162q',
  'Find Your Way Back to Me, My Childhood Sweetheart': 'https://reelslink.com/cps/SPopnS',
  'Fix You': 'https://reelslink.com/cps/JLfVup',
  'Football GOAT Reincarnated Into Me': 'https://reelslink.com/cps/iRZZvd',
  'God of Snow': 'https://reelslink.com/cps/KIirHr',
  'Group Chat Divinity': 'https://reelslink.com/cps/HRIqON',
  'He Pulled a Prank on Me and Lost Everything': 'https://reelslink.com/cps/Q2u5ch',
  'His Partner, Her Revenge': 'https://reelslink.com/cps/gg9GEG',
  'How to Wreck My Bully\'s Heart': 'https://reelslink.com/cps/XDElGI',
  'I Married the Alpha They Threw Away': 'https://reelslink.com/cps/knFGff',
  'I Only Have Brisket for You': 'https://reelslink.com/cps/iq6MRw',
  'Illegal Touching': 'https://reelslink.com/cps/0yHvae',
  'Keeping the Cowboy\'s Baby': 'https://reelslink.com/cps/KImKer',
  'King of the Flooded World': 'https://reelslink.com/cps/Ngw4b2',
  'Love Caught Fangs and Claws': 'https://reelslink.com/cps/9aaojH',
  'Match Point': 'https://reelslink.com/cps/dbd8aq',
  'Max Maid’s Survival Rules': 'https://reelslink.com/cps/ZMhbnV',
  'My Billionaire Husband Left Me for Him？': 'https://reelslink.com/cps/HzsgoX',
  'My Ex-Wife Wants Me Back Too Late': 'https://reelslink.com/cps/hzXlDA',
  'My Fiancé Betrayed Me, So I Bankrupted Him': 'https://reelslink.com/cps/LedTya',
  'My Secret Affair with the Duke': 'https://reelslink.com/cps/xxx9WI',
  'My Secret Alpha is My Lucky Puppy': 'https://reelslink.com/cps/mHeHqM',
  'My Useless Husband Is an Immortal': 'https://reelslink.com/cps/T3cnYC',
  'My Vampire Lord': 'https://reelslink.com/cps/6bzFu5',
  'My Wife Replaced Me With An AI Lover': 'https://reelslink.com/cps/Bp3Hwo',
  'My Wolf is the Sun God': 'https://reelslink.com/cps/42vJo0',
  'Never Reject A Wolf Princess': 'https://reelslink.com/cps/HNNb0G',
  'Nothing Escapes My Eyes': 'https://reelslink.com/cps/1RMxKK',
  'Pregnant with Power': 'https://reelslink.com/cps/HIIoSi',
  'Promise in Paper, Folded Vow': 'https://reelslink.com/cps/Uqe1YJ',
  'Rustblade Witcher': 'https://reelslink.com/cps/O0VTIp',
  'Secret Marriage Swap, The War God’s Late Remorse': 'https://reelslink.com/cps/7T4hJ7',
  'Seduced by My Boyfriend’s Uncle': 'https://reelslink.com/cps/KJVMz7',
  'Stardust and Lies': 'https://reelslink.com/cps/xUabPE',
  'That Beggar Wants Out': 'https://reelslink.com/cps/rdlYLV',
  'The Alpha King\'s Virgin Bride': 'https://reelslink.com/cps/oOPuNR',
  'The Alpha Made His Savior the Pack\'s Slave': 'https://reelslink.com/cps/jVVtOP',
  'The Alpha\'s Unclaimed Mate—I Rose to Lycan Royalty': 'https://reelslink.com/cps/CJJUA1',
  'The Beast King Worships the Worthless': 'https://reelslink.com/cps/agfSeL',
  'The Billionaire Married a Homeless Girl': 'https://reelslink.com/cps/SmG5br',
  'The Blacksmith You Dumped Is the Red Dragon King': 'https://reelslink.com/cps/b57b2H',
  'The Boss Affair': 'https://reelslink.com/cps/Sg5yBL',
  'The Crown of Thorns and Tide': 'https://reelslink.com/cps/n1rhmX',
  'The Deadliest Operative Alive': 'https://reelslink.com/cps/hD3hzJ',
  'The Diary of a Workshop Veteran': 'https://reelslink.com/cps/nr2n62',
  'The Elf Queen\'s Revenge': 'https://reelslink.com/cps/7jLPNi',
  'The Fake Dating Spell': 'https://reelslink.com/cps/bh2AQM',
  'The Fake Hero Never Saw Me Coming': 'https://reelslink.com/cps/YBiQ9P',
  'The Frank Method': 'https://reelslink.com/cps/NcodcE',
  'The Lycan\'s Savage Luna': 'https://reelslink.com/cps/YEYSnQ',
  'The Mafia Boss My Husband Betrayed': 'https://reelslink.com/cps/Bu0WN8',
  'The Photo that Changed Everything': 'https://reelslink.com/cps/2qDwPz',
  'The Proctologist\'s Brother': 'https://reelslink.com/cps/usTQCz',
  'The Silent Luna’s Secret': 'https://reelslink.com/cps/MJaoIe',
  'The Siren\'s Vengeance': 'https://reelslink.com/cps/45E3p3',
  'The Surgeon You Shouldn\'t Have Crossed': 'https://reelslink.com/cps/OXouSK',
  'The Tyrant\'s Max-Level Dragon Bride': 'https://reelslink.com/cps/B83qyp',
  'The Vampire Prince\'s Bride': 'https://reelslink.com/cps/dKKGLa',
  'The Veteran’s Promise': 'https://reelslink.com/cps/85qeXj',
  'They Bet I\'d Cry, I Bet They\'d Fall': 'https://reelslink.com/cps/6UcBTB',
  'Trash Boy\'s Super Watch': 'https://reelslink.com/cps/QZHmZT',
  'Where the Stars Went': 'https://reelslink.com/cps/deg9rj',
  'Wolfless? Bow to the Queen!': 'https://reelslink.com/cps/ypplt1',
  'You Fired A Tech Genius': 'https://reelslink.com/cps/sChVOH',
  'You\'ve Been Replaced, First Love': 'https://reelslink.com/cps/VE04zG',
  'Zero to Alpha: Return of the Wolf King': 'https://reelslink.com/cps/8AgjMz',
};
